name: Set up Launchable
description: >-
  Install the required dependencies and execute the necessary Launchable commands for test recording

inputs: {} # nothing?

outputs: {} # nothing?

runs:
  using: composite

  steps:
    # Launchable CLI requires Python and Java
    # https://www.launchableinc.com/docs/resources/cli-reference/
    - name: Set up Python
      uses: actions/setup-python@871daa956ca9ea99f3c3e30acb424b7960676734 # v5.0.0
      with:
        python-version: "3.10"

    - name: Set up Java
      uses: actions/setup-java@7a445ee88d4e23b52c33fdc7601e40278616c7f8 # v4.0.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Launchable
      shell: bash
      run: |
        set -x
        pip install launchable
        launchable verify
        : # The build name cannot include a slash, so we replace the string here.
        github_ref="$(echo ${{ github.ref }} | sed 's/\//_/g')"
        : # With the --name option, we need to configure a unique identifier for this build.
        : # To avoid setting the same build name as the CI which runs on other branches, we use the branch name here.
        : #
        : # FIXME: Need to fix `WARNING: Failed to process a change to a file`.
        : # https://github.com/launchableinc/cli/issues/786
        launchable record build --name ${github_ref}_${GITHUB_PR_HEAD_SHA}
        echo "TESTS=${TESTS} --launchable-test-reports=launchable_reports.json" >> $GITHUB_ENV
