name: Ubuntu
on:
  push:
    paths-ignore:
      - 'doc/**'
      - '**/man'
      - '**.md'
      - '**.rdoc'
      - '**/.document'
      - '.*.yml'
  pull_request:
    # Do not use paths-ignore for required status checks
    # https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks
  merge_group:

env:
  # GITHUB_PULL_REQUEST_URL are used for commenting test reports in Launchable Github App.
  # https://github.com/launchableinc/cli/blob/v1.80.1/launchable/utils/link.py#L42
  GITHUB_PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
  # The following envs are necessary in Launchable tokenless authentication.
  # https://github.com/launchableinc/cli/blob/v1.80.1/launchable/utils/authentication.py#L20
  LAUNCHABLE_ORGANIZATION: ${{ github.repository_owner }}
  LAUNCHABLE_WORKSPACE: ${{ github.event.repository.name }}
  # https://github.com/launchableinc/cli/blob/v1.80.1/launchable/utils/authentication.py#L71
  GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  # This secret setting is needed if you want to run Launchable on your forked
  # repository.
  # See https://github.com/ruby/ruby/wiki/CI-Servers#launchable-ci for details.
  LAUNCHABLE_TOKEN: ${{ secrets.LAUNCHABLE_TOKEN }}

concurrency:
  group: ${{ github.workflow }} / ${{ startsWith(github.event_name, 'pull') && github.ref_name || github.sha }}
  cancel-in-progress: ${{ startsWith(github.event_name, 'pull') }}

permissions:
  contents: read

jobs:
  make:
    strategy:
      matrix:
        test_task: [check]
        test_opts: ['']
        arch: ['']
        configure: ['cppflags=-DVM_CHECK_MODE']
        # specifying other jobs with `include` to avoid redundant tests
        include:
          - test_task: check
            arch: i686
          - test_task: check
            configure: '--disable-yjit'
          - test_task: check
            configure: '--enable-shared --enable-load-relative'
          - test_task: test-bundler-parallel
          - test_task: test-bundled-gems
      fail-fast: false

    env:
      GITPULLOPTIONS: --no-tags origin ${{ github.ref }}
      RUBY_DEBUG: ci

    runs-on: ubuntu-20.04

    if: >-
      ${{!(false
      || contains(github.event.head_commit.message, '[DOC]')
      || contains(github.event.pull_request.title, '[DOC]')
      || contains(github.event.pull_request.labels.*.name, 'Documentation')
      || (github.event_name == 'push' && github.actor == 'dependabot[bot]')
      )}}

    steps:
      - name: Enable Launchable conditionally
        id: enable_launchable
        run: echo "enable_launchable=true" >> $GITHUB_OUTPUT
        working-directory:
        if: >-
          ${{
          (github.repository == 'ruby/ruby' ||
          (github.repository != 'ruby/ruby' && env.LAUNCHABLE_TOKEN)) &&
          (matrix.test_task == 'check' || matrix.test_task == 'test-all')
          }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          sparse-checkout-cone-mode: false
          sparse-checkout: /.github

      - uses: ./.github/actions/setup/ubuntu
        with:
          arch: ${{ matrix.arch }}

      - uses: ./.github/actions/setup/directories
        with:
          srcdir: src
          builddir: build
          makeup: true
          dummy-files: ${{ matrix.test_task == 'check' }}

      - uses: ruby/setup-ruby@d4526a55538b775af234ba4af27118ed6f8f6677 # v1.172.0
        with:
          ruby-version: '3.0'
          bundler: none

      - name: Run configure
        env:
          arch: ${{ matrix.arch }}
          configure: ${{ matrix.configure }}
        run: >-
          $SETARCH ../src/configure -C --disable-install-doc ${configure:-cppflags=-DRUBY_DEBUG}
          ${arch:+--target=$arch-$OSTYPE --host=$arch-$OSTYPE}

      - run: $SETARCH make prepare-gems
        if: ${{ matrix.test_task == 'test-bundled-gems' }}

      - run: $SETARCH make

      - name: Set test options for skipped tests
        run: |
          set -x
          TESTS="$(echo "${{ matrix.skipped_tests }}" | sed 's| |$$/ -n!/|g;s|^|-n!/|;s|$|$$/|')"
          echo "TESTS=${TESTS}" >> $GITHUB_ENV
        if: ${{ matrix.test_task == 'check' && matrix.skipped_tests }}

      - name: Set up Launchable
        uses: ./.github/actions/setup/launchable/setup
        if: steps.enable_launchable.outputs.enable_launchable

      - name: make ${{ matrix.test_task }}
        run: >-
          $SETARCH make -s ${{ matrix.test_task }}
          ${TESTS:+TESTS="$TESTS"}
          ${{ !contains(matrix.test_task, 'bundle') && 'RUBYOPT=-w' || '' }}
        timeout-minutes: 40
        env:
          RUBY_TESTOPTS: '-q --tty=no'
          TEST_BUNDLED_GEMS_ALLOW_FAILURES: 'minitest,test-unit,debug,bigdecimal,drb,typeprof'
          PRECHECK_BUNDLED_GEMS: 'no'

      - name: make skipped tests
        run: |
          $SETARCH make -s test-all TESTS="${TESTS//-n!\//-n/}"
        env:
          GNUMAKEFLAGS: ''
          RUBY_TESTOPTS: '-v --tty=no'
        if: ${{ matrix.test_task == 'check' && matrix.skipped_tests }}
        continue-on-error: ${{ matrix.continue-on-skipped_tests || false }}

      - name: Record test results in Launchable
        uses: ./.github/actions/setup/launchable/record-test
        with:
          os: ubuntu-20.04
        if: ${{ always() && steps.enable_launchable.outputs.enable_launchable }}

      - uses: ./.github/actions/slack
        with:
          label: ${{ matrix.test_task }} ${{ matrix.configure }}${{ matrix.arch }}
          SLACK_WEBHOOK_URL: ${{ secrets.SIMPLER_ALERTS_URL }} # ruby-lang slack: ruby/simpler-alerts-bot
        if: ${{ failure() }}

  result:
    if: ${{ always() }}
    name: ${{ github.workflow }} result
    runs-on: ubuntu-latest
    needs: [make]
    steps:
      - run: exit 1
        working-directory:
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}

defaults:
  run:
    working-directory: build
